[package]
name = "rdupes"
version = "0.1.0"
authors = ["Edward George <edwardgeorge@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake2 = "0.8.1"
clap = "2.33.0"
digest = "0.8.1"
